"""edit order table

Revision ID: 3a8ce70755a3
Revises: cd20641542b0
Create Date: 2026-04-22 19:12:05.415390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a8ce70755a3"
down_revision: Union[str, Sequence[str], None] = "cd20641542b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    order_type_enum = ENUM("PICKUP", "DELIVERY", name="ordertype", create_type=True)
    order_type_enum.create(op.get_bind(), checkfirst=True)

    order_status_enum = ENUM(
        "PENDING",
        "CONFIRMED",
        "READY",
        "COMPLETED",
        "CANCELLED",
        name="orderstatus",
        create_type=True,
    )
    order_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "order_items",
        sa.Column("item_total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
    )
    op.drop_column("order_items", "subtotal")
    op.add_column(
        "orders",
        sa.Column(
            "order_type",
            sa.Enum("PICKUP", "DELIVERY", name="ordertype"),
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
    )
    op.add_column("orders", sa.Column("desired_time", sa.DateTime(), nullable=False))
    op.add_column("orders", sa.Column("delivery_address", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("delivery_entrance", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("delivery_floor", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("delivery_intercom", sa.String(), nullable=True))
    op.drop_constraint(op.f("orders_cart_id_fkey"), "orders", type_="foreignkey")
    op.drop_column("orders", "cart_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "sessions", type_="unique")
    op.drop_constraint(None, "products", type_="unique")
    op.add_column(
        "orders", sa.Column("cart_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("orders_cart_id_fkey"), "orders", "carts", ["cart_id"], ["id"]
    )
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_column("orders", "delivery_intercom")
    op.drop_column("orders", "delivery_floor")
    op.drop_column("orders", "delivery_entrance")
    op.drop_column("orders", "delivery_address")
    op.drop_column("orders", "desired_time")
    op.drop_column("orders", "status")
    op.drop_column("orders", "order_type")
    op.add_column(
        "order_items",
        sa.Column(
            "subtotal",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "order_items", type_="unique")
    op.drop_column("order_items", "item_total_price")
    op.drop_constraint(None, "categories", type_="unique")
    op.drop_constraint(None, "carts", type_="unique")
    op.drop_constraint(None, "cart_items", type_="unique")
    # ### end Alembic commands ###
