"""add image column to product

Revision ID: 8f1b04a73ced
Revises: e36f5dceb4d5
Create Date: 2026-03-02 21:14:30.596978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f1b04a73ced"
down_revision: Union[str, Sequence[str], None] = "e36f5dceb4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image")
    # ### end Alembic commands ###
